modLoader="javafml" #mandatory
loaderVersion="[28.1]" #mandatory
[[mods]] #mandatory
modId="spudergy" #mandatory
version="0.1" #mandatory
displayName="Spudergy" #mandatory
description='''
Tater's are pretty neat.
'''

[[dependencies.spudergy]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.spudergy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
